### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by iskrisis** [jongacnik/rploy#1]
Hi! Great little project i have made essentially the same thing https://github.com/floriankarsten/kirby3-mix-build-kit/blob/next/deploy.js but yours is much nicer and i would love to switch to something public. I have few things this doesn't handle are you OK with possible PRs?

My main problem is working with content folder in kirby. I deploy without content but i would also need to pull content from site and in very rare occasions push content back to a site.

Maybe there is minimal way that would just switch configuration based on argument.

Something like
```javascript
{
  "rploy": {
    "source": "public/",
    "destination": "user@ip:/var/www/public/",
    "configurations": {
      "getcontent": {
        // your config from here
        "source": "user@ip:/var/www/public/content",
        "destination": "public/content",
      }
    }
  }
}
```
that would enable `npx rploy getcontent`

Btw i had no idea about lifecycle scripts pretty great thanks!

**Comment by jongacnik** [comment]
Hey, yeah, have been wanting to get a mechanism like this in for pulling from remote and etc. I think a decent key for it could be `contexts` and would imagine it working like you mention, etc:

```js
{
  "rploy": {
    "contexts": {
      "pull": {
        "source": "user@ip:/var/www/public/",
        "destination": "public"
      },
      "pushcontent": {
        "source": "user@ip:/var/www/public/content/",
        "destination": "public/content"
      },
      "pullcontent": {
        "source": "public/content/",
        "destination": "user@ip:/var/www/public/content"
      }
    }
  }
}
```

I think ideally it should still function with the existing `branches` concept, so you can have branches per context (or maybe contexts per branch). The reason being, you would be able to run `npx rploy pull` and depending on what branch you are working on locally, it would pull from the correct remote destination. So a possible way to think about the config when using branches could be something like:

```js
{
  "rploy": {
    "contexts": {
      "pull": {
        "branches": {
          "master": "user@ip:/var/www/prod/public/",
          "dev": "user@ip:/var/www/dev/public/"
        },
        "destination": "public"
      }
    }
  }
}
```

**Comment by iskrisis** [comment]
Also i've realized i am pretty dumb. When i need to get just one folder from server i can use rsync directly in npm script. It becomes hustle with excludes and branches etc. but for one folder it's unnecessary  abstraction.

**Comment by jongacnik** [comment]
Yeah you definitely could. Still think this *could* be an ok add since it's nice to have all configs in one spot, but will think on it a little more.
