### ISSUE TITLE
Allow `rploy.config.json` file

### ISSUE THREAD

**Issue by arnoson** [jongacnik/rploy#5]
I sometimes find it a bit messy to have long configurations (in my case a lot of excludes and some includes) in the package.json. A seperate json file as an alternaive would be great. Rploy could check if a file called `rploy.config.json` exists and as a fallback use the package.json.

What do you think?
I would be happy to open a PR if you are interested in this feature.

**Comment by jongacnik** [comment]
Yeah, am fine with an external config. Happy to review a PR if you want. Wonder if a `js` file is better, just in the event you want to use some logic or etc to build up options.

**Comment by moevbiz** [comment]
i would love to see an update like this! another advantage imo would be that the js file could load data from a `.env` file; or that you wouldn't even have to commit this file at all – i'm not 100% comfortable having a hard coded `user@ip` in `package.json` in a public repo

**Comment by arnoson** [comment]
I'm a bit busy right now and don't think I'll have time soon but I'm also still interested in the feature

**Comment by moevbiz** [comment]
created a pull request

**Comment by moevbiz** [comment]
ah, maybe the version number should be bumped so that this new feature will be included on npm

**Comment by jongacnik** [comment]
Oof good catch, moving too quick over here. Should be all set now.
