### ISSUE TITLE
Error: Cannot find module 'app-root-path'

### ISSUE THREAD

**Issue by iskrisis** [jongacnik/rploy#7]
Version 1.1 seems to break the classic configuration in package.json. Or is that not supported anymore?

**Comment by jongacnik** [comment]
I probably didn't do my due diligence testing the last pull request >.< I'll have a look later

**Comment by iskrisis** [comment]
Also sorry for the shit issue. I am in middle of project launch so i couldn't investigate further. I will have look at it next week.

**Comment by jongacnik** [comment]
Haha, no worries, I know how it goes. Same over here, gonna try to have a look this afternoon.

**Comment by iskrisis** [comment]
Fixed with https://github.com/jongacnik/rploy/pull/8

**Comment by moevbiz** [comment]
i believe this error was due to the mentioned package not being required in package.json, my bad for forgetting that. config from package.json definitely worked when i tested
edit: ah but reading in the PR right now that it was an unnecessary `require` statement... sorry for breaking

**Comment by iskrisis** [comment]
@moevbiz can you check if the PR is working for your situation so this could potentionally be merged? As far as i understand you are using `rploy.config.js` because you made the initial PR.

**Comment by jongacnik** [comment]
Merged #8
